openapi: 3.0.0
info:
  title: Blogging Platform API
  description: A blogging platform that allows users to manage posts
  version: 1.0.0
servers:
  - url: https://virtserver.swaggerhub.com/CARINACMEIRELES/Blogging_Platform_API/1.0.0
    description: SwaggerHub API Auto Mocking
  - url: http://localhost:3000
    description: Local Development Server
paths:
  /posts:
    get:
      description: "Retrieve a list of blog posts, optionally filtered by a search term"
      parameters:
        - name: term
          in: query
          description: "Filter blog posts by a specific search term within the title, content or category"
          required: false
          style: form
          explode: true
          schema:
            type: string
      responses:
        "200":
          description: Successful pull of blog posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Posts"
        "400":
          description: Failed to find specific search term
        "500":
          description: Database error
    post:
      description: Creates a new blog post in the database
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Post"
        required: true
      responses:
        "201":
          description: Successful creation of a new blog post
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Post"
        "400":
          description: Failed to create a new blog post
        "500":
          description: Database error
  /posts/{id}:
    get:
      description: Retrieve a single blog post by ID
      parameters:
        - name: id
          in: path
          description: The unique ID of the blog post
          required: true
          style: simple
          explode: false
          schema:
            type: integer
      responses:
        "200":
          description: Successful pull of a specific blog post
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Post"
        "404":
          description: Failed to find the specific blog post
        "500":
          description: Database error
    put:
      description: Update an existing blog post
      parameters:
        - name: id
          in: path
          description: The unique ID of the blog post
          required: true
          style: simple
          explode: false
          schema:
            type: integer
      responses:
        "200":
          description: Successful update of a specific blog post
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Post"
        "400":
          description: Failed to update specific blog post
        "500":
          description: Database error
    delete:
      description: Delete an existing blog post
      parameters:
        - name: id
          in: path
          description: The unique ID of the blog post
          required: true
          style: simple
          explode: false
          schema:
            type: integer
      responses:
        "204":
          description: Successfull deletion of a specific blog post
        "404":
          description: Failed to find the specific blog post
        "500":
          description: Database error
components:
  schemas:
    Posts:
      type: array
      description: Array of blog info
      items:
        $ref: "#/components/schemas/Post"
    Post:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: My First Blog Post
        content:
          type: string
          example: This is the content of my first blog post.
        category:
          type: string
          example: Technology
        tags:
          type: array
          example:
            - Tech
            - Programming
          items:
            type: string
      description: Model containing blog info
